---
# Main block so we can pass uri module defaults througout the role
- name: "Satellite6 Manage Content Views"
  block:
    - name: "Ensure we have the Satellite Server's CA for validating authentication"
      stat:
        path: "/etc/pki/ca-trust/source/anchors/katello-server-ca.crt"
      register: "ca_cert"

    - name: "Obtain Satellite Server's CA for validating authentication"
      block:
        - name: "Download CA Certificate"
          get_url:
            url: "http://{{ sat6_fqdn }}/pub/katello-server-ca.crt"
            dest: "/etc/pki/ca-trust/source/anchors/katello-server-ca.crt"

        - name: "Update CA trust"
          command: "update-ca-trust"
      when: "not ca_cert.stat.exists"
      become: True

    - name: "Obtain Satellite6 Organization ID"
      block:
        - name: "Obtain Satellite6 Organization ID"
          uri:
            body: "{\"search\": 'name=\"{{ sat6_organization }}\"'}"
          register: "org_qry"
          vars:
            sat6_url_path: "api/v2/organizations"

        - debug:
            var: "org_qry.json.results[0]"
            verbosity: "1"

        - name: "Set Satellite6 Organization ID"
          set_fact:
            organization_id: "{{ org_qry.json.results[0].id }}"
          when: "org_qry.json.results[0].name == sat6_organization"

        - debug:
            var: "organization_id"
            verbosity: "1"
      tags:
        - "organization_id"

    - name: "Set initial statistics"
      set_fact:
        content_views_published: "0"
        content_views_published_names: []
        content_views_promoted: "0"
        content_views_promoted_names: []
        content_views_versions_removed: "0"
        content_views_versions_removed_names: []
        composite_content_view_components_updated: "0"
        composite_content_view_components_updated_names: []
        composite_content_views_published: "0"
        composite_content_views_published_names: []

    - name: "Manage Content Views"
      include_tasks: "manage_content_views.yml"
      with_items: "{{ sat6_content_views }}"
      loop_control:
        loop_var: "cv"
        label: "{{ cv.name }}"
      when: "sat6_content_views | length > 0"
  always:
    #reporting statistics of actions
    #  Set fact so we can re-use in email notifications or other tasks outside the role
    - name: "Set statistics output"
      set_fact:
        sat6_content_view_stats:
          - "Total content views published: {{ content_views_published }}"
          - "Content views published:"
          - "{{ content_views_published_names }}"
          - "Total composite content views published: {{ composite_content_views_published }}"
          - "Composite content views published:"
          - "{{ composite_content_views_published_names }}"
          - "Total content view promotions: {{ content_views_promoted }}"
          - "Content views promoted:"
          - "{{ content_views_promoted_names }}"
          - "Total composite content view component updates: {{ composite_content_view_components_updated }}"
          - "Composite content view components updated:"
          - "{{ composite_content_view_components_updated_names }}"
          - "Total content view versions removed: {{ content_views_versions_removed }}"
          - "Content view versions removed:"
          - "{{ content_views_versions_removed_names }}"

    - name: "Report content view changes"
      debug:
        msg: "{{ sat6_content_view_stats }}"
      when: "sat6_content_view_show_stats | default(True)"

# set uri module on main block, which cascades defaults to all uri module calls, avoiding repetitive params
  module_defaults:
    uri:
      user: "{{ sat6_user }}"
      password: "{{ sat6_pass }}"
      force_basic_auth: True
      url: "https://{{ sat6_fqdn }}/{{ sat6_url_path | default('') }}"
      method: "GET"
      status_code: "200"
      body_format: "json"
      timeout: "120"
