---
- name: "Clear facts"
  set_fact:
    content_view_id: ""
    content_view_composite: ""
    content_view_published: False
    remove_content_view_version_ids: []
    composite_content_view_id: ""
    composite_components: []
    composite_auto_publish: False

- name: "Obtain content view ID"
  block:
    - name: "Obtain {{ cv.name }} content view data"
      include_tasks: "get_content_views.yml"

    - name: "Set {{ cv.name }} content view facts"
      set_fact:
        content_view_id: "{{ cv_qry.json.results[0].id }}"
        content_view_composite: "{{ cv_qry.json.results[0].composite | bool }}"
      when: 'cv.name == cv_qry.json.results[0].name'

    - debug:
        var: "content_view_id"
        verbosity: "1"

    - debug:
        var: "content_view_composite"
        verbosity: "1"

    - name: "Set composite content view facts"
      set_fact:
        composite_content_view_id: "{{ cv_qry.json.results[0].id }}"
        composite_components: "{{ cv_qry.json.results[0] | json_query(ccv_comp_jq) }}"
        composite_auto_publish: "{{ cv_qry.json.results[0].auto_publish | bool }}"
      vars:
        ccv_comp_jq: "content_view_components[*].{name: content_view.name, cv_id: content_view.id, comp_id: id}"
      when: "content_view_composite | bool"


# TODO:
# - name: "Create content view"
#   block:
#
#   when:
#     - 'content_view_id == ""'
#     - 'cv.create_on_missing | default(False)'

- name: "Publish new content view version"
  include_tasks: "publish_content_view.yml"
  when:
    - "cv.publish_new_version | default(False) | bool"
    - "not content_view_composite | bool"
    - "content_view_id != ''"

- name: "Publish new composite content view version"
  include_tasks: "publish_composite_content_view.yml"
  when:
    - "cv.publish_new_version | default(False) | bool"
    - "content_view_composite | bool"
    - "composite_content_view_id != ''"
    - "not composite_auto_publish | bool"

- name: "Promote content view to lifecycle environments"
  include_tasks: "promote_content_view.yml"
  when:
    - "cv.promote_to | default([]) | length > 0"

- name: "Remove previous content view version"
  include_tasks: "remove_prev_cv_ver.yml"
  when:
    - "cv.promote_remove_previous_version | default(False) | bool"
    - "cv.promote_to | default([]) | length > 0" #only delete when we promote
    - "cv_vers | default([]) | length > 1" #make sure we have more than 1 version
    - "content_view_published | bool"
  vars:
    cv_id_jq: "versions[*].id"
    cv_vers: "{{ cv_qry.json.results[0] | json_query(cv_id_jq) }}"

- debug:
    msg:
      - "Not attempting to remove previous content view version for one of the following reasons:"
      - "    A content view was not published during this run"
      - "    There was less than 2 content view versions, so we do not want to try and delete the only one we have."
  when: (not content_view_published | bool and
          cv.promote_remove_previous_version | default(False) | bool) or
        (cv_vers | length < 2 and
          cv.promote_remove_previous_version | default(False) | bool)
  vars:
    cv_id_jq: "versions[*].id"
    cv_vers: "{{ cv_qry.json.results[0] | json_query(cv_id_jq) }}"

- name: "Keep specified number of content view versions"
  block:
    - name: "Obtain latest {{ cv.name }} content view data"
      include_tasks: "get_content_views.yml"

    - name: "Build list of content views to remove"
      include_tasks: "build_cv_keep_list.yml"

    - name: "Remove old content view versions, keeping {{ cv.keep_content_view_versions_count }}"
      include_tasks: "remove_cv_vers.yml"
      with_items: "{{ cv_remove_list }}"
      loop_control:
        loop_var: "version"
        label: "{{ version.name }}"
      when: "cv_remove_list | length > 0"

    - debug:
        msg:
          - "Not attempting to remove old content view versions."
          - "The specified number of versions to keep was {{ cv.keep_content_view_versions_count }}"
          - "There are currently {{ cv_keep_list | length }} versions that exist, from a total of {{ cv_ver_names | length }}"
          - "The remove list length is not greater than 0"
      when: "cv_remove_list | length < 1"
  when: "cv.keep_content_view_versions_count | default('') != ''"

- name: "Remove specified content view version(s)"
  block:
    - name: "Set content view version ID"
      include_tasks: "build_cv_remove_list.yml"
      with_items: "{{ cv.remove_content_view_versions }}"
      loop_control:
        loop_var: "version"

    - name: "Remove content view versions"
      include_tasks: "remove_cv_vers.yml"
      with_items: "{{ remove_content_view_version_ids }}"
      loop_control:
        loop_var: "version"
        label: "{{ version.name }}"
  when: "cv.remove_content_view_versions | default([]) | length > 0"
