---
- name: "Clear facts"
  set_fact:
    content_view_id: ""
    content_view_composite: ""

- name: "Obtain content view ID"
  block:
    - name: "Obtain content view ID"
      uri:
        body: "{\"search\": 'name=\"{{ cv.name }}\"', \"organization_id\": \"{{ organization_id }}\"}"
      register: "cv_qry"
      vars:
        sat6_url_path: "katello/api/content_views"

    - debug:
        var: "cv_qry.json.results[0]"
        verbosity: "1"

    - name: "Set content view facts"
      set_fact:
        content_view_id: "{{ cv_qry.json.results[0].id }}"
        content_view_composite: "{{ cv_qry.json.results[0].composite | bool }}"
      when: 'cv.name == cv_qry.json.results[0].name'

    - debug:
        var: "content_view_id"
        verbosity: "1"

    - debug:
        var: "content_view_composite"
        verbosity: "1"
  tags:
    - "content_view_id"

# TODO:
# - name: "Create content view"
#   block:
#
#   when:
#     - 'content_view_id == ""'
#     - 'cv.create_on_missing | default(False)'

- name: "Publish new content view version"
  block:
    - name: "Initiate publishing new content view version of {{ cv.name }}"
      uri:
        method: "POST"
        status_code: "202"
        body: "{\"description\": \"{{ cv.publish_description | default('') }}\",
                \"force_yum_metadata_regeneration\": \"{{ cv.publish_force_yum_metadata_regeneration | default(False) }}\"
              }"
      vars:
        sat6_url_path: "katello/api/content_views/{{ content_view_id }}/publish"
      register: "cv_publish"

    - debug:
        var: "cv_publish.json"
        verbosity: "1"

    - name: "Check {{ cv.name }} content view publish status"
      uri:
        body: "{\"id\": \"{{ cv_publish.json.id }}\"}"
      register: "cv_publish_qry"
      vars:
        sat6_url_path: "foreman_tasks/api/tasks/{{ cv_publish.json.id }}"
      until:
        - "cv_publish_qry.json.state == 'stopped'"
        - "not cv_publish_qry.json.pending | bool"
        - "cv_publish_qry.json.progress | string == '1.0'"
        - "cv_publish_qry.json.result == 'success'"
      changed_when: "cv_publish_qry.json.result == 'success'"
      failed_when:
        - "cv_publish_qry.json.state == 'paused'"
        - "cv_publish_qry.json.result == 'error'"
      retries: "240"
      delay: "30"

    - debug:
        var: "cv_publish_qry.json"
        verbosity: "1"
  when:
    - "cv.publish_new_version | default(False)"
    - "not content_view_composite"
    - "content_view_id != ''"
  tags:
    - "publish_content_view"

- name: "Lifecycle environments"
  block:
    - name: "Obtain lifecycle environments"
      uri:
        body: "{\"per_page\": \"1000\"}"
      register: "lifecycle_qry"
      vars:
        sat6_url_path: "katello/api/environments"

    - debug:
        var: "lifecycle_qry"
        verbosity: "1"

    - name: "Obtain content view facts"
      block:
        - name: "Obtain content view Version ID"
          uri:
            body: "{\"search\": 'name=\"{{ cv.name }}\"',
                    \"organization_id\": \"{{ organization_id }}\"
                  }"
          register: "cv_ver_qry"
          vars:
            sat6_url_path: "katello/api/content_views"

        - debug:
            var: "cv_ver_qry.json.results[0]"
            verbosity: "1"

        - name: "Set content view facts"
          set_fact:
            content_view_version_id: "{{ cv_ver_qry.json.results[0] | json_query(cv_id_jq) | max }}"
          vars:
            cv_id_jq: "versions[*].id"

        - name: "Set {{ cv.name }} latest version promotion list"
          set_fact:
            content_view_environment_ids: "{{ cv_ver_qry.json.results[0] | json_query(cv_env_ids_jq) | flatten }}"
          vars:
            cv_env_ids_jq: "versions[?id==`{{ content_view_version_id }}`].environment_ids"

        - debug:
            var: "content_view_version_id"
            verbosity: "1"

        - name: "Clean Library from content_view_environment_ids"
          set_fact:
            content_view_environment_ids: "{{ content_view_environment_ids | difference([1]) }}"
          when: "1 in content_view_environment_ids"

        - debug:
            var: "content_view_environment_ids"
            verbosity: "1"
      tags:
        - "content_view_facts"

    - name: "Set lifecycle environment id list"
      set_fact:
        lifecycle_ids: []
        lifecycle_dicts: []

    - name: "Build lifecycle environment id list"
      include_tasks: "build_promotion_list.yml"
      with_items: "{{ cv.promote_to }}"
      loop_control:
        loop_var: "lifecycle"
        label: "{{ lifecycle }}"

    - debug:
        var: "lifecycle_ids | difference(content_view_environment_ids)"
        verbosity: "1"

    - debug:
        var: "lifecycle_dicts"
        verbosity: "1"

    - name: "Promote content view to lifecycle environments"
      include_tasks: "promote_to_lifecycle.yml"
      when: "lifecycle_ids | difference(content_view_environment_ids) | length > 0"

    - debug:
        msg:
          - "Not attempting to promote {{ cv.name }}."
          - "The current content view version (id: {{ content_view_version_id }}) has already been promoted to {{ lifecycles }}."
      when: "lifecycle_ids | difference(content_view_environment_ids) | length < 1"
      vars:
        lifecycles: "{{ cv.promote_to | join(', ') }}"

  tags:
    - "promote_cv_to_lifecycle"
  when:
    - "cv.promote_to | default('[]') | length > 0"
