---
- name: "Obtain lifecycle environments"
  uri:
    body: "{\"per_page\": \"1000\"}"
  register: "lifecycle_qry"
  vars:
    sat6_url_path: "katello/api/environments"

- debug:
    var: "lifecycle_qry"
    verbosity: "1"

- name: "Obtain latest content views"
  include_tasks: "get_content_views.yml"

- name: "Set content view facts"
  set_fact:
    content_view_version_id: "{{ cv_qry.json.results[0] | json_query(cv_id_jq) | max }}"
  vars:
    cv_id_jq: "versions[*].id"

- name: "Set {{ cv.name }} latest version promotion list"
  set_fact:
    content_view_environment_ids: "{{ cv_qry.json.results[0] | json_query(cv_env_ids_jq) | flatten }}"
  vars:
    cv_env_ids_jq: "versions[?id==`{{ content_view_version_id }}`].environment_ids"

- debug:
    var: "content_view_version_id"
    verbosity: "1"

- name: "Clean Library from content_view_environment_ids"
  set_fact:
    content_view_environment_ids: "{{ content_view_environment_ids | difference([1]) }}"
  when: "1 in content_view_environment_ids"

- debug:
    var: "content_view_environment_ids"
    verbosity: "1"

- name: "Set lifecycle environment id list"
  set_fact:
    lifecycle_ids: []
    lifecycle_dicts: []

- name: "Build lifecycle environment id list"
  include_tasks: "build_promotion_list.yml"
  with_items: "{{ cv.promote_to }}"
  loop_control:
    loop_var: "lifecycle"
    label: "{{ lifecycle }}"

- debug:
    var: "lifecycle_ids | difference(content_view_environment_ids)"
    verbosity: "1"

- debug:
    var: "lifecycle_dicts"
    verbosity: "1"

- name: "Promote content view to lifecycle environments"
  include_tasks: "promote_to_lifecycle.yml"
  when: "lifecycle_ids | difference(content_view_environment_ids) | length > 0"

- debug:
    msg:
      - "Not attempting to promote {{ cv.name }}."
      - "The current content view version (id: {{ content_view_version_id }}) has already been promoted to {{ lifecycles }}."
  when: "lifecycle_ids | difference(content_view_environment_ids) | length < 1"
  vars:
    lifecycles: "{{ cv.promote_to | join(', ') }}"
